# Generated by Django 4.2.12 on 2025-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0003_alter_claimant_date_issued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimant",
            name="date_issued",
            field=models.DateField(auto_now=True),
        ),
    ]
