# Generated by Django 4.2.12 on 2025-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0004_alter_claimant_date_issued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimant",
            name="claim_type",
            field=models.CharField(
                choices=[
                    ("motor", "Motor Insurance"),
                    ("medical", "Medical Insurance"),
                    ("property", "Property Insurance"),
                    ("life", "Life Insurance"),
                    ("travel", "Travel Insurance"),
                    ("agriculture", "Agricultural Insurance"),
                    ("workmen", "Workmen’s Compensation"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
