# Generated by Django 4.2.12 on 2025-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0005_alter_claimant_claim_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimant",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
