# Generated by Django 4.2.12 on 2025-07-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0006_claimant_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MakeYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="make",
                        to="claim.make",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=10)),
                ("engine_capacity", models.CharField(max_length=100)),
                ("engine_number", models.CharField(max_length=100)),
                ("chassis_number", models.CharField(max_length=100)),
                (
                    "vehicle_use",
                    models.CharField(
                        blank=True,
                        choices=[("commercial", "Commercial"), ("private", "Private")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("cover_end", models.DateField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model",
                        to="claim.model",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="make",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="make_year",
                to="claim.makeyear",
            ),
        ),
    ]
