# Generated by Django 4.2.12 on 2025-07-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("claim", "0007_make_makeyear_model_product_make_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=10)),
                ("engine_capacity", models.CharField(max_length=100)),
                ("engine_number", models.CharField(max_length=100)),
                ("chassis_number", models.CharField(max_length=100)),
                (
                    "vehicle_use",
                    models.CharField(
                        blank=True,
                        choices=[("commercial", "Commercial"), ("private", "Private")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("cover_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model",
                        to="claim.model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
