# Generated by Django 4.2.12 on 2025-07-21 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("claim", "0008_quotation_delete_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Claimant",
            new_name="Claim",
        ),
        migrations.RenameField(
            model_name="claimfile",
            old_name="claimant",
            new_name="claim",
        ),
    ]
