# Generated by Django 4.2.12 on 2025-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0009_rename_claimant_claim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="has_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="insured_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
