# Generated by Django 4.2.12 on 2025-07-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0010_quotation_has_paid_quotation_insured_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="quotation",
            field=models.FileField(default=True, upload_to="quotation_files/"),
            preserve_default=False,
        ),
    ]
