# Generated by Django 4.2.12 on 2025-07-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0011_quotation_quotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="quotation",
            field=models.FileField(blank=True, null=True, upload_to="quotation_files/"),
        ),
    ]
